[package]
name = "discord_stat"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.61"
discord = { git = "https://github.com/o0Ignition0o/discord-rs" }

